baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Zhuo Wu Blog'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Welcome to my world"
Content = "Self introduction"

[[params.socialIcons]]
name = "Linkedin"
url = "www.linkedin.com/in/zhuo-wu-762383268"

[[params.socialIcons]]
name = "Github"
url = "<link2>"


[params]
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true


[outputs]
home = [ "HTML", "RSS", "JSON" ]